#!/bin/sh /etc/rc.common
                                    
START=30
STOP=90

RUN_DIR="/var/run"

config_cb(){
	local name="$1"
	local cfg="$2"

	[ -n "$cfg" ] && {
		rm -f $RUN_DIR/chilli_$cfg*
		CONFIG_FILE="$RUN_DIR/chilli_$cfg.conf"
	}
}

option_cb(){
	local option="$1"
	local value="$2"

	case "$option" in
		enabled) 
			[ "$value" == "0" ] && {
				logger -s -t "Coovachilli" "Covachilli is disabled in /etc/config/coovachilli"
				exit 0
			} 
			;;
		uamdomain_*) ;;
		network)
			. /lib/functions/network.sh
			local ifname
			network_get_device ifname $value
			[ -n "$ifname" ] || {
				exit 1
			}
			echo "dhcpif=\"$ifname\"" >> $CONFIG_FILE
			;;
		# boolean settings
		dhcpbroadcast|nodynip|vlanlocation|locationstopstart|locationcopycalled|locationimmediateupdate|locationopt82|coanoipcheck|noradallow|proxymacaccept|proxyonacct|dhcpmacset|dhcpradius|noc2c|eapolenable|uamanydns|uamanyip|uamnatanyip|nouamsuccess|nowispr1|nowispr2|domaindnslocal|radsec|macauth|macreauth|macauthdeny|macallowlocal|strictmacauth|strictdhcp|ieee8021q|only8021q|radiusoriginalurl|swapoctets|statusfilesave|wpaguests|openidauth|papalwaysok|mschapv2|chillixml|acctupdate|dnsparanoia|seskeepalive|usetap|noarpentries|framedservice|scalewin|redir|injectwispr|redirurl|routeonetone|nousergardendata|uamgardendata|uamotherdata|withunixipc|uamallowpost|redirssl|uamuissl|layer3|patricia|redirdnsreq|dhcpnotidle|ipv6|ipv6only)
			[ "$value" = "true" -o "$value" = "1" ] && echo "$option" >> $CONFIG_FILE
			;;
		*)
			echo "$option=\"$value\"" >> $CONFIG_FILE
			;;
	esac
}

list_cb(){
	local option="$1"
	local value="$2"
	echo "$option=\"$value\"" >> $CONFIG_FILE
}

config_coovachilli() {
	local cfg="$1"
	local base="/var/run/chilli_${cfg}"

	logger -s -t "Coovachilli" "Starting coovachilli"
	chilli -c ${base}.conf --pidfile ${base}.pid --cmdsocket ${base}.sock --unixipc ${base}.ipc &
	return 0
}

start() {
	config_load chilli
	config_foreach config_coovachilli chilli
}

stop() {                                                       
	ls $RUN_DIR/chilli*.pid 2>/dev/null && {
		kill $(cat $RUN_DIR/chilli*.pid)
		sleep 1
		killall -9 chilli
		rm -f $RUN_DIR/chilli*
	}
}
